export const Routes = {
    root: '/',
    cart: '/cart',
    orders: '/orders',
    confirm: '/confirm',
    login: '/login',
    register: '/register',
    singleProduct: '/products',
    categories: '/categories',
    profile: '/profile',
    reset: '/reset/password',
    auction: '/auction',
    auctionProduct: '/auction/product',
    createAuctionProduct: '/auction/product/create',
};